package com.yhrjkf.woyundong.bean.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CUSER_BEAN".
*/
public class CUserBeanDao extends AbstractDao<CUserBean, Long> {

    public static final String TABLENAME = "CUSER_BEAN";

    /**
     * Properties of entity CUserBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MPhone = new Property(1, String.class, "mPhone", false, "M_PHONE");
        public final static Property MPassword = new Property(2, String.class, "mPassword", false, "M_PASSWORD");
        public final static Property MSpassword = new Property(3, String.class, "mSpassword", false, "M_SPASSWORD");
    }


    public CUserBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CUserBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CUSER_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"M_PHONE\" TEXT," + // 1: mPhone
                "\"M_PASSWORD\" TEXT," + // 2: mPassword
                "\"M_SPASSWORD\" TEXT);"); // 3: mSpassword
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CUSER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CUserBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mPhone = entity.getMPhone();
        if (mPhone != null) {
            stmt.bindString(2, mPhone);
        }
 
        String mPassword = entity.getMPassword();
        if (mPassword != null) {
            stmt.bindString(3, mPassword);
        }
 
        String mSpassword = entity.getMSpassword();
        if (mSpassword != null) {
            stmt.bindString(4, mSpassword);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CUserBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mPhone = entity.getMPhone();
        if (mPhone != null) {
            stmt.bindString(2, mPhone);
        }
 
        String mPassword = entity.getMPassword();
        if (mPassword != null) {
            stmt.bindString(3, mPassword);
        }
 
        String mSpassword = entity.getMSpassword();
        if (mSpassword != null) {
            stmt.bindString(4, mSpassword);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CUserBean readEntity(Cursor cursor, int offset) {
        CUserBean entity = new CUserBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mPhone
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mPassword
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // mSpassword
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CUserBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMPhone(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMPassword(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMSpassword(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CUserBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CUserBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CUserBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
